apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - metallb-native.yaml
  - traefik-ipaddresspool.yaml
  - traefik-l2advertisement.yaml

patchesStrategicMerge:
  - patch-metallb-speaker-talos.yaml
  - patch-metallb-namespace.yaml