# helm upgrade --install cilium cilium/cilium \
#   --version 1.18.0 \
#   --namespace kube-system \
#   -f values.yaml

# cilium connectivity test --connect-timeout 0s

cni:
  resources:
    requests:
      cpu: 500m
      memory: 200Mi

operator:
  replicas: 1

hostPort:
  enabled: false

ipam:
  mode: kubernetes

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN,KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUI
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

kubeProxyReplacement: false

hubble:
  enabled: false
  relay:
    enabled: false
  ui:
    enabled: false
  # metrics:
  #   enabled:
  #     - dns:query;ignoreAAAA
  #     - drop
  #     - tcp
  #     - flow
  #     - icmp
  #     - http
  tls:
    auto:
      enabled: true
      method: helm
      certValidityDuration: 1095
  peerService:
    clusterDomain: cluster.local
