# helm upgrade --install cilium cilium/cilium \
#   --version 1.17.5 \
#   --namespace kube-system \
#   -f values.yaml

# cilium connectivity test --connect-timeout 0s

operator:
  replicas: 1

hostPort:
  enabled: false
bpf:
  hostLegacyRouting: true

ipam:
  mode: kubernetes

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN,KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUI
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

kubeProxyReplacement: true
k8sServiceHost: "localhost"
k8sServicePort: "7445"

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - icmp
      - http
