preUpgradeChecker:
  jobEnabled: false
defaultSettings:
  defaultReplicaCount: 1
  defaultDataPath: /var/lib/longhorn
  storageOverProvisioningPercentage: 200
  storageMinimalAvailablePercentage: 5
  allowRecurringJobWhileVolumeDetached: true
  replicaSoftAntiAffinity: true
  autoSalvage: true
  concurrentReplicaRebuildPerNodeLimit: 2
  disableRevisionCounter: true
persistence:
  reclaimPolicy: Retain
  defaultClassReplicaCount: 1
  defaultDataLocality: best-effort
  disableRevisionCounter: true
  recurringJobSelector:
    enable: true
image:
  csi:
    attacherReplicaCount: 1
    provisionerReplicaCount: 1
    resizerReplicaCount: 1
    snapshotterReplicaCount: 1