preUpgradeChecker:
  jobEnabled: false

defaultSettings:
  defaultReplicaCount: 1
  defaultDataPath: /var/lib/longhorn
  storageOverProvisioningPercentage: 200
  storageMinimalAvailablePercentage: 5
  allowRecurringJobWhileVolumeDetached: true
  autoSalvage: true
  concurrentReplicaRebuildPerNodeLimit: 2

persistence:
  reclaimPolicy: Delete
  defaultClassReplicaCount: 1
  recurringJobSelector:
    enable: true

image:
  csi:
    attacherReplicaCount: 1
    provisionerReplicaCount: 1
    resizerReplicaCount: 1
    snapshotterReplicaCount: 1

metrics:
  serviceMonitor:
    enabled: true