apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tailscale-immich
  namespace: immich
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/tailnet-ip: "100.100.9.9"
    tailscale.com/hostname: "immich.typhon-neon.ts.net"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: immich-server
      port:
        number: 2283
        