apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobooks-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn
  volumeName: audiobooks-pv
