apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-1 # THIS NAME IS REQUIRED FOR CNPG
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
  volumeName: immich-db-pv