apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podcasts-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: longhorn
  volumeName: podcasts-pv
