apiVersion: v1
kind: PersistentVolume
metadata:
  name: podcasts-pv
  finalizers:
    - manishreddy.uk/finalizer
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  volumeMode: Filesystem
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: podcasts-pv
