apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podgrab-downloads-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: longhorn
  volumeName: podgrab-downloads-pv
