apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
  volumeName: syncthing-pv
