apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecrets-tailscale-operator
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: talos
        envSlug: prod
        secretsPath: "/tailscale-operator/"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: operator-oauth
      secretNamespace: tailscale
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true
        data:
          client_id: "{{ .TAILSCALE_OPERATOR_CLIENT_ID.Value }}"
          client_secret: "{{ .TAILSCALE_OPERATOR_CLIENT_SECRET.Value }}"
