# ingressRoutes:
# - id: argocd
#   namespace: argocd
#   serviceName: argocd-server
#   servicePort: 80
#   serversTransport: true|false
#   middleware:
#     type: redirect|auth|ipallowlist
#     redirectPath: k10/
---
ingressRoutes:
  - id: argocd
    namespace: argocd
    serviceName: argocd-server
    servicePort: 443
    serversTransport: true
    selector: 
      app.kubernetes.io/name: argocd-server
    podIngressPort: 8080

  - id: kasten
    namespace: kasten-io
    serviceName: gateway
    servicePort: 80
    redirectPath: "k10/"
    selector: 
      app.kubernetes.io/name: k10
    podIngressPort: 8000

  - id: longhorn
    namespace: longhorn-system
    serviceName: longhorn-frontend
    servicePort: 80
    redirectPath: "#/dashboard"
    headers: 
      - X-Forwarded-Proto: "https"
    selector: 
      app.kubernetes.io/name: longhorn
    podIngressPort: 8000

  - id: hubble
    namespace: kube-system
    serviceName: hubble-ui
    servicePort: 80
    selector: 
      app.kubernetes.io/name: hubble-ui
    podIngressPort: 8081