# namespaceIsolation:
  # - 
ingressRoutes:
  - id: argocd
    namespace: argocd
    serviceName: argocd-server
    appName: argocd-server
    servicePort: 443
    serversTransport: true
    podPort: 8080
    podProtocol: TCP
    authentik: false

  - id: kasten
    namespace: kasten-io
    serviceName: gateway
    appName: k10
    component: gateway
    servicePort: 80
    redirectPath: "k10/"
    podPort: 8000
    podProtocol: TCP

  - id: longhorn
    namespace: longhorn-system
    serviceName: longhorn-frontend
    app: longhorn-ui
    servicePort: 80
    redirectPath: "#/dashboard"
    headers:
      - X-Forwarded-Proto: "https"
    podPort: 8000
    podProtocol: TCP

  - id: hubble
    namespace: kube-system
    serviceName: hubble-ui
    appName: hubble-ui
    servicePort: 80
    podPort: 8081
    podProtocol: TCP
    authentik: false

  - id: authentik
    namespace: authentik
    serviceName: authentik-server
    appName: authentik
    servicePort: 443
    serversTransport: true
    podPort: 9443
    podProtocol: TCP

  # - id: velero
  #   namespace: velero
  #   serviceName: velero-velero-ui
  #   appName: velero
  #   servicePort: 80
  #   podPort: 3000
  #   podProtocol: TCP

  - id: grafana
    namespace: monitoring-system
    serviceName: grafana-service
    app: grafana
    servicePort: 3000
    podPort: 3000
    podProtocol: TCP

  # - id: prometheus
  #   namespace: monitoring-system
  #   serviceName: prometheus-kube-prometheus-prometheus
  #   servicePort: 9090
  #   appName: prometheus
  #   headers:
  #     - X-Forwarded-Proto: "https"
  #   podPort: 9090
  #   podProtocol: TCP
