apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn  # Must match the PV
  volumeName: pvc-0d232cbb-5d20-4439-a8d5-05712689f2fc  # The existing PV name