apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-prometheus-kube-prometheus-prometheus-db-prometheus-prometheus-kube-prometheus-prometheus-0
  namespace: monitoring-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn  # Must match the PV
  volumeName: pvc-e8146eb3-0024-4477-91da-9b12673c46d3  # The existing PV name