apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: netpol-traefik-pod
  namespace: tailscale
spec:
  endpointSelector:
    matchLabels:
      tailscale.com/parent-resource: traefik
  egress:
    - toEntities:
        - host
      toPorts:
        - ports:
            - port: "5351"
              protocol: UDP
            - port: "1900"
              protocol: UDP
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "1900"
              protocol: UDP
            - port: "34553"
              protocol: UDP
            - port: "34604"
              protocol: UDP
            - port: "33388"
              protocol: UDP
            - port: "5351"
              protocol: UDP
            - port: "41641"
              protocol: UDP
            - port: "3478"
              protocol: UDP

