apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: netpol-tailscale-common
  namespace: tailscale
spec:
  endpointSelector:
    matchLabels: {}
  ingress:
    - fromEndpoints:
        - {}
  egress:
    - toEndpoints:
        - {}
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "80"
              protocol: TCP
