apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-podcasts
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: longhorn

