apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-audiobookshelf-metadata
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn

