apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-podgrab-downloads
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn
