apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-audiobookshelf-config
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn

