{{- range .Values.ingressRoutes }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .id }}-ingressroute
  namespace: {{ .namespace }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: {{ printf "Host(`%s.talos.manishreddy.uk`)" .id | quote }}
      kind: Rule
      
      {{- if or (or .redirectPath .headers) .authentikMiddleware }}
      middlewares:
      {{- if .redirectPath }}
        - name: {{ .id }}-redirect
      {{- end }}
      {{- if .headers }}
        - name: {{ .id }}-headers
      {{- end }}
      {{- if (default true .authentik) }}
        - name: middleware-authentik-forwardauth
      {{- end }}
      
      services:
        - name: {{ .serviceName }}
          port: {{ .servicePort }}
          {{- if .serversTransport }}
          serversTransport: "serverstransport-{{ .id }}"
          {{- end }}    
  tls:
    certResolver: cloudflare
---
{{- end }}