{{- range .Values.ingressRoutes }}
{{- if .headers }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .id }}-headers
  namespace: {{ .namespace }}
spec:
  headers:
    customRequestHeaders:
      {{- range $key, $value := .headers }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
---
{{- end }}
{{- end }}
