{{- range .Values.ingressRoutes }}
{{- if .redirectPath }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .id }}-redirect
  namespace: {{ .namespace }}
spec:
  redirectRegex:
    regex: ^https?://{{ .id }}.talos\.manishreddy\.uk/?$
    replacement: https://{{ .id }}.talos.manishreddy.uk/{{ .redirectPath }}
    permanent: true
---
{{- end }}
{{- end }}
