{{- range .Values.ingressRoutes }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "ui-ingress-{{ .id}}"
  namespace: monitoring-system
spec:
  endpointSelector:
    matchLabels:
        k8s:io.kubernetes.pod.namespace: {{ .namespace }}
      {{- if .appName }}
        app.kubernetes.io/name: {{ .appName }}
      {{- else if .k8sAppName }}
        k8s:k8s-app: {{ .k8sAppName }}
      {{- else }}
        app: {{ .app }}
      {{- end }}
      {{- if .component }}
        component: {{ .component }}
      {{ - end}}
  ingress:
  - fromEndpoints:
    - matchLabels: {}
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: traefik
        app.kubernetes.io/name: traefik
    toPorts:
    - ports:
      - port: "{{ .podPort }}"
        protocol: {{ .podProtocol }}
{{- end }}