apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: argocd-allow-traefik
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: traefik
