namespaceOverride: monitoring-system

alertmanager:
  namespaceOverride: monitoring-system

grafana:
  namespaceOverride: monitoring-system

kube-state-metrics:
  namespaceOverride: monitoring-system

prometheus-node-exporter:
  namespaceOverride: monitoring-node-exporter