apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd # This manifest's namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Ensure child resources are cleaned up before the app is deleted
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  sources:
    - repoURL: "https://grafana.github.io/helm-charts"
      chart: grafana-operator
      targetRevision: 5.*.*
      helm:
        valueFiles:
          - $values/grafana-operator/values.yaml # Path to values file in this repo
    - repoURL: "https://github.com/mani-sh-reddy/argocd.git"
      targetRevision: main
      ref: values
    - repoURL: https://github.com/mani-sh-reddy/argocd.git
      path: grafana-operator-manifests/
      targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring-system # Where components live
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
