apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-operator
  namespace: argocd # This manifest's namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Ensure child resources are cleaned up before the app is deleted
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  sources:
    - repoURL: "https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/"
      chart: secrets-operator
      targetRevision: 0.*.*
      helm:
        valueFiles:
          - $values/infisical-operator/values.yaml # Path to values file in this repo
    - repoURL: "https://github.com/mani-sh-reddy/argocd.git"
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "infisical" # Where components live
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
