apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kasten-manifests
  namespace: argocd # This manifest's namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Ensure child resources are cleaned up before the app is deleted
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  destination:
    namespace: kasten-io
    server: https://kubernetes.default.svc
  source:
    path: kasten-manifests/
    repoURL: https://github.com/mani-sh-reddy/argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
  ignoreDifferences:
    - group: ""
      kind: Service
      name: expose-apollo
      namespace: kasten-io
      jsonPointers:
        - /spec/externalName
