apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-manifests
  namespace: argocd # This manifest's namespace
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  source:
    path: longhorn-manifests/
    repoURL: https://github.com/mani-sh-reddy/argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true