apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/metallb/metallb
      targetRevision: v0.15.2
      path: config/manifests/metallb-native
    - repoURL: https://github.com/mani-sh-reddy/argocd.git
      targetRevision: HEAD
      path: metallb/
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
