apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-system-manifests
  namespace: argocd # This manifest's namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Ensure child resources are cleaned up before the app is deleted
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  destination:
    namespace: monitoring-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: monitoring-system-manifests/
    repoURL: https://github.com/mani-sh-reddy/argocd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true