apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd # This manifest's namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Ensure child resources are cleaned up before the app is deleted
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  sources:
    - repoURL: "https://pkgs.tailscale.com/helmcharts"
      chart: tailscale-operator
      targetRevision: 1.*.*
      helm:
        valueFiles:
          - $values/tailscale-operator/values.yaml # Path to values file in this repo
    - repoURL: "https://github.com/mani-sh-reddy/argocd.git"
      targetRevision: main
      ref: values
    - repoURL: https://github.com/mani-sh-reddy/argocd.git
      path: tailscale-manifests/
      targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: tailscale # Where components live
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/externalName
