apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-ingressroutes
  namespace: argocd # This manifest's namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Ensure child resources are cleaned up before the app is deleted
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/mani-sh-reddy/argocd.git
      targetRevision: HEAD
      path: traefik-ingressroutes/
      helm:
        valueFiles:
          - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik # Where components live
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
