apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: velero
 namespace: argocd # This manifest's namespace
 labels:
   app.kubernetes.io/managed-by: argocd
 finalizers:
   - resources-finalizer.argocd.argoproj.io # Ensure child resources are cleaned up before the app is deleted
spec:
 project: default
 sources:
   - repoURL: "https://charts.kasten.io/"
     chart: velero
     targetRevision: 10.*.*
     helm:
       valueFiles:
         - $values/velero/values.yaml # Path to values file in this repo
   - repoURL: "https://github.com/mani-sh-reddy/argocd.git"
     targetRevision: main
     ref: values
   - repoURL: https://github.com/mani-sh-reddy/argocd.git
     path: velero-manifests/
     targetRevision: HEAD
 destination:
   server: "https://kubernetes.default.svc"
   namespace: velero # Where components live
 syncPolicy:
   automated:
     selfHeal: true
     prune: true
     allowEmpty: true
   syncOptions:
     - CreateNamespace=true