apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoriametrics
  namespace: argocd # This manifest's namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Ensure child resources are cleaned up before the app is deleted
  labels:
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  sources:
    - repoURL: "https://victoriametrics.github.io/helm-charts/"
      chart: victoria-metrics-operator
      targetRevision: *.*.*
      helm:
        valueFiles:
          - $values/victoriametrics-operator/values.yaml # Path to values file in this repo
    - repoURL: "https://github.com/mani-sh-reddy/argocd.git"
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: victoriametrics # Where components live
  syncPolicy:
    syncOptions:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#respect-ignore-difference-configs
    # argocd must also ignore difference during apply stage
    # otherwise it ll silently override changes and cause a problem
    - RespectIgnoreDifferences=true
    - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: victoriametrics-validation
      namespace: victoriametrics
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: victoriametrics-admission
      jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
