{{- range .Values.volumes }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}
  finalizers:
    - manishreddy.uk/finalizer
spec:
  capacity:
    storage: {{ .size }}
  accessModes:
    - {{ .accessMode | default "ReadWriteOnce" }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  volumeMode: Filesystem
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: {{ .name }}
{{- end -}}