{{- range .Values.volumes }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name | quote }}
  namespace: {{ .namespace | quote }}
spec:
  accessModes:
    - {{ .accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .size | quote }}
  storageClassName: longhorn
  volumeName: {{ .name | quote }}
{{- end -}}