apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: infisical-fetch-secrets
  namespace: infisical
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: secrets-operator
  egress:
    - toFQDNs:
        - matchName: app.infisical.com
      toPorts:
        - ports:
            - port: "443"