namespaceOverride: monitoring-system

pometheus:
  prometheusSpec:
    retention: 5y
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
          selector: 
            longhornvolume: cloned-pvc-3285f46e-bad0-4b82-9-ef03d97c
    # persistentVolumeClaimRetentionPolicy:
    #   whenDeleted: Retain
    #   whenScaled: Retain
    # podMonitorSelectorNilUsesHelmValues: false
    # ruleSelectorNilUsesHelmValues: false
    # serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  enabled: false
  # namespaceOverride: monitoring-system
  # defaultDashboardsTimezone: browser
  # persistence:
  #   enabled: true
  #   storageClassName: longhorn
  #   accessModes:
  #     - ReadWriteOnce
  #   size: 20Gi
  #   finalizers:
  #     - kubernetes.io/pvc-protection

kube-state-metrics:
  namespaceOverride: monitoring-system

prometheus-node-exporter:
  namespaceOverride: monitoring-node-exporter

alertmanager:
  enabled: false

prometheus-windows-exporter:
  enabled: false
# kubeControllerManager:
#   enabled: false

# kubeScheduler:
#   enabled: false

# kubeEtcd:
#   enabled: false
