namespaceOverride: monitoring-system
alertmanager:
  namespaceOverride: monitoring-system
kube-state-metrics:
  namespaceOverride: monitoring-system
prometheus-node-exporter:
  namespaceOverride: monitoring-node-exporter

prometheusSpec:
  retention: 5y
  volumeClaimTemplate:
   spec:
     storageClassName: longhorn
     accessModes: 
      - ReadWriteOnce
     resources:
       requests:
         storage: 50Gi
  podMonitorSelectorNilUsesHelmValues: false
  ruleSelectorNilUsesHelmValues: false
  serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  namespaceOverride: monitoring-system
  defaultDashboardsEditable: false
  defaultDashboardsTimezone: browser
  operator:
    dashboardsConfigMapRefEnabled: true
  persistence:
    enabled: true
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    finalizers:
      - kubernetes.io/pvc-protection

# kubeControllerManager:
#   enabled: false

# kubeScheduler:
#   enabled: false

# kubeEtcd:
#   enabled: false