namespaceOverride: monitoring-system
alertmanager:
  namespaceOverride: monitoring-system
kube-state-metrics:
  namespaceOverride: monitoring-system
prometheus-node-exporter:
  namespaceOverride: monitoring-node-exporter

prometheusSpec:
  retention: 5y
  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podMonitorSelectorNilUsesHelmValues: false
  ruleSelectorNilUsesHelmValues: false
  serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  namespaceOverride: monitoring-system
  defaultDashboardsTimezone: browser
  persistence:
    enabled: true
    storageClassName: longhorn
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    finalizers:
      - kubernetes.io/pvc-protection
# kubeControllerManager:
#   enabled: false

# kubeScheduler:
#   enabled: false

# kubeEtcd:
#   enabled: false
