{
 "title": "Talos K8s",
 "tags": [ "Talos K8s" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kubelet_running_pods)" }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cluster:node_cpu:ratio_rate5m" }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum) / sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Prometheus TSDB Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(prometheus_tsdb_storage_blocks_bytes)",
     "legendFormat": "{{cluster}} {{job}} {{instance}} head series"
    }
   ]
  },
  {
   "title": "Prometheus Samples",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_samples_appended_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_containers)"
    }
   ]
  },
  { "title": "Compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(namespace) (container_memory_rss{container!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Volume Capacity",
   "type": "table",
   "description": "The capacity of each Longhorn volume",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (volume) (longhorn_volume_capacity_bytes)",
     "legendFormat": "{{volume}}"
    },
    {
     "expr": "avg by (volume, name) (\n  label_replace(kubelet_volume_stats_used_bytes, \"name\", \"$1\", \"persistentvolumeclaim\", \"(.*)\")\n  * on(name) group_left(volume)\n  (\n    label_replace(kube_persistentvolume_claim_ref, \"volume\", \"$1\", \"persistentvolume\", \"(.*)\")\n  )\n)",
     "legendFormat": "{{volume}}"
    },
    {
     "expr": "100 / avg by (volume) (longhorn_volume_capacity_bytes)\r\n*\r\navg by (volume) (\r\n  label_replace(kubelet_volume_stats_used_bytes, \"name\", \"$1\", \"persistentvolumeclaim\", \"(.*)\")\r\n  * on(name) group_left(volume, persistentvolume)\r\n  (\r\n    label_replace(kube_persistentvolume_claim_ref, \"volume\", \"$1\", \"persistentvolume\", \"(.*)\")\r\n  )\r\n)",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "gauge",
   "description": "The capacity of each Longhorn volume",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(longhorn_disk_usage_bytes/longhorn_disk_capacity_bytes)*100"
    }
   ]
  }
 ]
}