namespaceOverride: keycloak
resourcesPreset: "medium"

## @param production Run Keycloak in production mode. TLS configuration is required except when using proxy=edge.
##
production: true
## @param proxyHeaders Set Keycloak proxy headers
##
proxyHeaders: "xforwarded"

auth:
  ## @param auth.adminUser Keycloak administrator user
  ##
  adminUser: admin
  ## @param auth.adminPassword Keycloak administrator password for the new user
  ##
  adminPassword: admin
  # ## @param auth.existingSecret Existing secret containing Keycloak admin password
  # ##
  # existingSecret: ""
  # ## @param auth.passwordSecretKey Key where the Keycloak admin password is being stored inside the existing secret.
  # ##
  # passwordSecretKey: ""

postgresql:
  enabled: true
  auth:
    postgresPassword: "supersecretpostgrespass"
    username: bn_keycloak
    password: "bn_keycloak"
    database: bitnami_keycloak
    existingSecret: keycloak-postgresql
    # secretKeys:
    #   userPasswordKey: password
  # architecture: standalone