# apiVersion: v1
# kind: Pod
# metadata:
#   name: acme-permissions-fixer
#   namespace: traefik
# spec:
#   restartPolicy: Never
#   initContainers:
#     - name: acme-volume-permissions
#       image: busybox:latest
#       command:
#         - sh
#         - -c
#         - |
#           touch /data/acme.json && \
#           chmod 600 /data/acme.json && \
#           chown 65532:65532 /data/acme.json
#       securityContext:
#         runAsUser: 0
#       volumeMounts:
#         - name: data
#           mountPath: /data
#   containers:
#     - name: sleep
#       image: busybox:latest
#       command: ["sh", "-c", "sleep 3600"]
#       volumeMounts:
#         - name: data
#           mountPath: /data
#   volumes:
#     - name: data
#       persistentVolumeClaim:
#         claimName: traefik-data

