ingressRoute:
  dashboard:
    enabled: true
    matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
    services:
      - name: api@internal
        kind: TraefikService
    entryPoints: ["traefik"]

providers:
  kubernetesCRD:
    allowCrossNamespace: true

global:
  checkNewVersion: true
  sendAnonymousUsage: false

envFrom:
  - secretRef:
      name: traefik-dns-acme-secret

ports:
  web:
    port: 80
    expose:
      default: true
    exposedPort: 80
    protocol: TCP
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    port: 443
    hostPort:
    containerPort:
    expose:
      default: true
    exposedPort: 443

service:
  enabled: true
  single: true
  type: ClusterIP
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/tailnet-ip: "100.100.99.99"
    tailscale.com/hostname: "traefik"
  labels:
    app: traefik

persistence:
  enabled: true
  # existingClaim: traefik-data
  storageClass: ceph-filesystem
  accessMode: ReadWriteOnce
  size: 128Mi
  path: /data

certificatesResolvers:
  cloudflare:
    acme:
      storage: /data/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - "9.9.9.9:53"
          - "1.1.1.1:53"

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true

podSecurityContext:
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

experimental:
  fastProxy:
    enabled: true