global:
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secret-key
          key: AUTHENTIK_SECRET_KEY
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-auth
          key: AUTHENTIK_POSTGRESQL_USER_PASSWORD

authentik:
  secret_key: "env://AUTHENTIK_SECRET_KEY"
  password: "env://AUTHENTIK_POSTGRESQL__PASSWORD"

worker:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      memory: 1Gi

server:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      memory: 1Gi

postgresql:
  enabled: true
  auth:
    username: authentik
    database: authentik
    existingSecret: authentik-postgres-auth
    secretKeys:
      adminPasswordKey: AUTHENTIK_POSTGRESQL_ADMIN_PASSWORD
      userPasswordKey: AUTHENTIK_POSTGRESQL_USER_PASSWORD
      replicationPasswordKey: AUTHENTIK_POSTGRESQL_REPLICATION_PASSWORD
    usePasswordFiles: false
  persistence:
    enabled: true
    storageClass:
    accessModes:
      - ReadWriteOnce
    size: 8Gi

redis:
  enabled: true
