apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleaner-kastenpvcs-cronjob
  namespace: cleaners
spec:
  schedule: "0 9 * * *" # every day at 9am
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cleaner-kastenpvcs-serviceaccount
          containers:
            - name: pv-cleaner
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  apk add --no-cache jq
                  kubectl get pv -o json | jq -r '.items[] | select(.spec.claimRef.namespace == "kasten-io" and .status.phase == "Released") | .metadata.name' | while read pv; do
                    echo "Patching $pv"
                    kubectl patch pv "$pv" -p '{"spec":{"persistentVolumeReclaimPolicy":"Delete"}}'
                  done
          restartPolicy: Never
