apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleaner-kastenpvcs-cronjob
  namespace: cleaners
spec:
  schedule: "0 0 */3 * *"  # every 3 days at midnight
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cleaner-kastenpvcs-serviceaccount
          containers:
            - name: pv-cleaner
              image: bitnami/kubectl:latest
              command:
                - /bin/bash
                - -c
                - |
                  echo "Finding Released PVs with claimRef in kasten-io namespace and PVC starting kanister-pvc..."
                  PV_NAMES=$(kubectl get pv --no-headers | awk '$5=="Released" && $6 ~ /^kasten-io\/kanister-pvc/ {print $1}')
                  if [ -z "$PV_NAMES" ]; then
                    echo "No matching PVs found."
                  else
                    echo "Deleting PVs:"
                    echo "$PV_NAMES"
                    for pv in $PV_NAMES; do
                      kubectl delete pv "$pv"
                    done
                  fi
          restartPolicy: OnFailure