apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cleaner-kastenpvcs-clusterrole
  namespace: cleaners
rules:
  - apiGroups: ["longhorn.io"]
    resources: ["volumes", "engines", "snapshots", "volumeattachments"]
    verbs: ["get", "list", "delete"]