apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleaner-pod-cronjob
  namespace: cleaners
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cleaner-pod-serviceaccount
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  kubectl delete pod --field-selector=status.phase==Succeeded --all-namespaces
                  kubectl delete pod --field-selector=status.phase==Failed --all-namespaces
          restartPolicy: OnFailure
