kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: longhorn-snapshot-vsc
  annotations: 
    k10.kasten.io/is-snapshot-class: true
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: snap
