apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: custom
  namespace: argocd
spec:
  description: "One Application Per Namespace Guard Rails"
  sourceRepos:
    - 'https://github.com/mani-sh-reddy/argocd.git'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false