apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-dashboard
  namespace: argocd
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`argocd.talos.manishreddy.uk`)
      kind: Rule
      services:
        - name: argocd-server
          port: 443
          serversTransport: servertransport-argocd
  tls:
    certResolver: cloudflare
