apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secret-conf
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 10
  authentication:
      universalAuth:
          secretsScope:
              projectSlug: talos
              envSlug: prod
              secretsPath: "/"
          credentialsRef:
              secretName: universal-auth-credentials
              secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: managed-secret
      secretNamespace: infisical
      creationPolicy: "Owner"
      template:
        includeAllSecrets: true
        data:
          NEW_KEY_NAME: "{{ .KEY.SecretPath }} {{ .KEY.Value }}"
          KEY_WITH_BINARY_VALUE: "{{ .KEY.SecretPath }} {{ .KEY.Value }}"