apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: whole-cluster
  namespace: kasten-io
spec:
  actions:
    - action: backup
      backupParameters:
        ignoreExceptions: true
    - action: export
      exportParameters:
        migrationToken:
          name: whole-cluster-migration-token
          namespace: kasten-io
  comment: Whole Cluster Backup
  presetRef:
    name: hourly-snapshots-daily-export
    namespace: kasten-io
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - kasten-io-cluster
          - argocd
          - cilium-secrets
          - cleaners
          - default
          - infisical
          - kube-system
          - kubelet-serving-cert-approver
          - longhorn-system
          - monitoring-node-exporter
          - monitoring-system
          - tailscale
          - traefik
          - authentik
