apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: kasten-disaster-recovery
  namespace: kasten-io
  annotations:
    argocd.argoproj.io/tracking-id: k10:config.kio.kasten.io/Policy:kasten-io/k10-disaster-recovery-policy
spec:
  frequency: "@hourly"
  actions:
    - action: backup
      backupParameters:
        filters: {}
        profile:
          name: apollo-minio-s3
          namespace: kasten-io
    - action: export
      exportParameters:
        frequency: "@hourly"
        profile:
          name: apollo-minio-s3
          namespace: kasten-io
        exportData:
          enabled: true
  subFrequency:
    weekdays:
      - 0
    days:
      - 1
    months:
      - 1
  backupWindow:
    start:
      hour: 4
      minute: 0
    end:
      hour: 5
      minute: 0
  enableStaggering: false
  retention:
    hourly: 2
    daily: 7
    weekly: 5
    monthly: 3
    yearly: 1
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - kasten-io
  kdrSnapshotConfiguration:
    takeLocalCatalogSnapshot: true
    exportCatalogSnapshot: true
