kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: k10-disaster-recovery-policy # name has to match default disaster recovery name
  namespace: kasten-io
spec:
  frequency: "@hourly"
  backupWindow:
    start:
      hour: 5
      minute: 0
    end:
      hour: 6
      minute: 0
  retention:
    hourly: 1
    daily: 7
    weekly: 5
    monthly: 3
    yearly: 1
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - kasten-io
  actions:
    - action: backup
      backupParameters:
        filters: {}
        profile:
          name: apollo-minio-s3
          namespace: kasten-io
    - action: export
      exportParameters:
        frequency: "@hourly"
        profile:
          name: apollo-minio-s3
          namespace: kasten-io
        exportData:
          enabled: true
      retention: {}
  createdBy: k10-admin
  modifiedBy: k10-admin
  kdrSnapshotConfiguration:
    takeLocalCatalogSnapshot: true
    exportCatalogSnapshot: true
