apiVersion: config.kio.kasten.io/v1alpha1
kind: PolicyPreset
metadata:
  name: hourly-snapshots-daily-export
  namespace: kasten-io
spec:
  backup:
    frequency: '@hourly'
    profile:
      name: apollo-minio-s3
      namespace: kasten-io
    retention:
      hourly: 12
      daily: 7
      monthly: 12
      weekly: 4
      yearly: 2
    subFrequency:
      days:
        - 1
      hours:
        - 3
      minutes:
        - 30
      months:
        - 1
      weekdays:
        - 0
  comment: Daily snapshots to Apollo Minio S3 bucket
  export:
    exportData:
      enabled: true
    frequency: '@daily'
    profile:
      name: apollo-minio-s3
      namespace: kasten-io
