apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: whole-cluster
  namespace: kasten-io
spec:
  actions:
    - action: backup
      backupParameters:
        ignoreExceptions: true
    - action: export
      exportParameters:
        migrationToken:
          name: whole-cluster-migration-token
          namespace: kasten-io
  comment: Whole Cluster Backup
  presetRef:
    name: hourly-snapshots-daily-export
    namespace: kasten-io
  selector:
    matchExpressions:
      # This first expression ensures the resource is managed by Kasten
      - key: k10.kasten.io/appNamespace
        operator: Exists
      # This second expression excludes the specified system namespaces
      - key: k10.kasten.io/appNamespace
        operator: NotIn
        values:
          - kube-system
          - kube-public
          - kube-node-lease
      # Backup all cluster scoped
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - kasten-io-cluster