apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: k10-disaster-recovery-policy
  namespace: kasten-io
spec:
  actions:
    - action: backup
      backupParameters:
        profile:
          name: apollo-minio-s3
          namespace: kasten-io
    - action: export
      exportParameters:
        exportData:
          enabled: true
        frequency: '@hourly'
        profile:
          name: apollo-minio-s3
          namespace: kasten-io
  frequency: '@hourly'
  kdrSnapshotConfiguration:
    exportCatalogSnapshot: true
    takeLocalCatalogSnapshot: true
  retention:
    daily: 2
    hourly: 2
    monthly: 2
    weekly: 2
    yearly: 2
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - kasten-io
