apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podcleaner-rolebinding
  namespace: podcleaner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podcleaner-clusterrole
subjects:
- kind: ServiceAccount
  name: podcleaner-serviceaccount
  namespace: podcleaner