apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecrets-kasten-cluster-receivestring
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: talos
        envSlug: prod
        secretsPath: "/kasten/"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: whole-cluster-migration-token
      secretNamespace: kasten-io
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: false
        data:
          migrationToken: "{{ .WHOLE_CLUSTER_MIGRATION_RECIEVESTRING.Value }}"
