apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecrets-grafana-admin
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: talos
        envSlug: prod
        secretsPath: "/monitoring-stack/"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: grafana-admin-credentials
      secretNamespace: monitoring-system
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: false
        data:
          GRAFANA_ADMIN_USERNAME: "{{ .GRAFANA_ADMIN_USERNAME.Value }}"
          GRAFANA_ADMIN_PASSWORD: "{{ .GRAFANA_ADMIN_PASSWORD.Value }}"
