apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecrets-netdata
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: talos
        envSlug: prod
        secretsPath: "/netdata/"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: netdata
      secretNamespace: monitoring-system
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: false
        data:
          NETDATA_CLAIM_TOKEN: "{{ .NETDATA_CLAIM_TOKEN.Value }}"
