apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecrets-velero-apollo-minio-access
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: talos
        envSlug: prod
        secretsPath: "/velero/"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: velero-apollo-minio-access
      secretNamespace: velero
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: false
        cloud: |
          aws_access_key_id: "{{ .S3_ACCESS_KEY_ID.Value }}"
          aws_secret_access_key: "{{ .S3_SECRET_ACCESS_KEY.Value }}"
