apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecrets-kasten-apollo-minio-accesskey
  annotations:
    secrets.kanister.io/type: aws
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: talos
        envSlug: prod
        secretsPath: "/kasten/"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: kasten-apollo-minio-accesskey
      secretNamespace: kasten-io
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: false
        data:
          aws_access_key_id: "{{ .S3_ACCESS_KEY_ID.Value }}"
          aws_secret_access_key: "{{ .S3_SECRET_ACCESS_KEY.Value }}"
