apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecrets-telegram-apollobot-token
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: talos
        envSlug: prod
        secretsPath: "/monitoring-system/"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: telegram-apollobot-token
      secretNamespace: monitoring-system
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: false
        data:
          TELEGRAM_APOLLOBOT_TOKEN: "{{ .TELEGRAM_APOLLOBOT_TOKEN.Value }}"
