apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecrets-authentik-postgres-auth
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: talos
        envSlug: prod
        secretsPath: "/authentik/"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: authentik-postgres-auth
      secretNamespace: authentik
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: false
        data:
          AUTHENTIK_POSTGRESQL_ADMIN_PASSWORD: "{{ .AUTHENTIK_POSTGRESQL_ADMIN_PASSWORD.Value }}"
          AUTHENTIK_POSTGRESQL_USER_PASSWORD: "{{ .AUTHENTIK_POSTGRESQL_USER_PASSWORD.Value }}"
          AUTHENTIK_POSTGRESQL_REPLICATION_PASSWORD: "{{ .AUTHENTIK_POSTGRESQL_REPLICATION_PASSWORD.Value }}"
