apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecrets-traefik-dns-acme
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: talos
        envSlug: prod
        secretsPath: "/traefik/"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: traefik-dns-acme-secret
      secretNamespace: traefik
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: false
        data:
          CLOUDFLARE_EMAIL: "{{ .CLOUDFLARE_EMAIL.Value }}"
          CLOUDFLARE_DNS_API_TOKEN: "{{ .CLOUDFLARE_DNS_API_TOKEN.Value }}"
          CLOUDFLARE_ZONE_API_TOKEN: "{{ .CLOUDFLARE_ZONE_API_TOKEN.Value }}"
