apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecrets-velero-apollo-minio-access
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: talos
        envSlug: prod
        secretsPath: "/longhorn/"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: longhorn-apollo-minio-access
      secretNamespace: longhorn
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: false
        data: 
          AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID.Value }}"
          AWS_ENDPOINTS: "{{ .AWS_ENDPOINTS.Value }}"
          AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY.Value }}"
