apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-db-pv
  finalizers:
    - manishreddy.uk/finalizer
spec:
  capacity:
    storage: 22362Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  volumeMode: Filesystem
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: immich-db-pv
