apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: x
  namespace: monitoring-system
spec:
  replicaCount: 1
  selectAllByDefault: true
  remoteWrite:
    - url: "http://vmsingle-x.monitoring.svc.cluster.local:8428/api/v1/write"