apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmagent-all-namespaces
rules:
  - apiGroups: ["operator.victoriametrics.com"]
    resources: ["vmnodescrapes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["endpoints", "pods", "services"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vmagent-all-namespaces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vmagent-all-namespaces
subjects:
  - kind: ServiceAccount
    name: vmagent-x
    namespace: monitoring-system