apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: x
  namespace: monitoring-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
  port: metrics
  interval: 10s