apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netdata-parent-database
  namespace: netdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn  # Must match the PV
  volumeName: pvc-1cdf2328-bc2d-4de3-abe2-b448efbfa93a  # The existing PV name