apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netdata-parent-database
  namespace: netdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn  # Must match the PV
  volumeName: pvc-90b1d68e-431e-4235-9e5c-ce888e23735b  # The existing PV name