apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netdata-k8s-state-varlib
  namespace: netdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn  # Must match the PV
  volumeName: pvc-f36bd559-1a05-4afb-906c-00f2322a9e22  # The existing PV name