apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netdata-k8s-state-varlib
  namespace: netdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn  # Must match the PV
  volumeName: pvc-1e155b41-bc61-4dc6-8f0e-0fd7813ec098  # The existing PV name