apiVersion: v1
kind: Service
metadata:
  name: svc-netdata-ui
  namespace: netdata
spec:
  selector:
    app: netdata
  ports:
    - name: http
      protocol: TCP
      port: 19999
      targetPort: 19999
  type: ClusterIP