image:
  tag: stable

restarter:
  enabled: false

ingress:
  enabled: false

parent:
  database:
    persistence: true
    storageclass: "longhorn"
    volumesize: 50Gi
  # env:
  #   DO_NOT_TRACK: 1
  envFrom:
    - secretRef:
        name: netdata
  claiming:
    enabled: true
    rooms: "c76cb402-1f1d-4cfc-bcb3-585dc9ec5281"

child:
  env:
    DO_NOT_TRACK: 1
  hostNetwork: false
  envFrom:
    - secretRef:
        name: netdata
  claiming:
    enabled: true
    rooms: "c76cb402-1f1d-4cfc-bcb3-585dc9ec5281"

k8sState:
  env:
    DO_NOT_TRACK: 1
  # envFrom:
  #   - secretRef:
  #       name: netdata
  # claiming:
  #   enabled: true
  #   rooms: "1197d4e3-4d17-4ce2-a678-31c4363e4571"
