image:
  tag: stable

restarter:
  enabled: false

ingress:
  enabled: false

parent:
  enabled: true
  hostname: "talos"
  database:
    persistence: true
    storageclass: "longhorn"
    volumesize: 100Gi
  envFrom:
    - secretRef:
        name: netdata
  claiming:
    enabled: true
    rooms: "55384689-a02b-45d6-81aa-3614cf7c9f16"
  configs:
    netdata:
      enabled: true
      path: /etc/netdata/netdata.conf
      data: |
        [global]
          hostname = talos
        [db]
          mode = dbengine
          storage tiers = 3
          dbengine tier 0 retention size = 40GiB
          dbengine tier 0 retention time = 3Mo
          dbengine tier 1 retention size = 30GiB
          dbengine tier 1 retention time = 12mo
          dbengine tier 2 retention size = 10GiB
          dbengine tier 2 retention time = 4y
        [plugins]
          cgroups = no
          tc = no
          enable running new plugins = no
          check for new plugins every = 72000
          python.d = no
          charts.d = no
          go.d = no
          node.d = no
          apps = no
          proc = no
          idlejitter = no
          diskspace = no
          devstat = no
          getmntinfo = no

child:
  dnsPolicy: ClusterFirst
  env:
    DO_NOT_TRACK: 1
  hostNetwork: false
  envFrom:
    - secretRef:
        name: netdata
  configs:
    netdata:
      enabled: true
      path: /etc/netdata/netdata.conf
      data: |
        [global]
          hostname = talos-collector
        [db]
          mode = dbengine
        [plugins]
          cgroups = yes
          tc = no
          enable running new plugins = no
          check for new plugins every = 72000
          python.d = no
          charts.d = yes
          go.d = yes
          node.d = yes
          apps = yes
          proc = yes
          idlejitter = no
          diskspace = yes
          devstat = yes
          getmntinfo = yes
    stream:
      enabled: true
      path: /etc/netdata/stream.conf
      data: |
        [stream]
          enabled = {{ ternary "yes" "no" .Values.parent.enabled }}
          destination = talos:{{ .Values.service.port }}
          api key = 11111111-2222-3333-4444-555555555555
          timeout seconds = 60
          buffer size bytes = 1048576
          reconnect delay seconds = 5
          initial clock resync iterations = 60
    go.d:
      enabled: true
      path: /etc/netdata/go.d.conf
      data: |
        modules:
          pulsar: no
          prometheus: yes
          traefik: yes

k8sState:
  hostname: talos-collector-k8s
  dnsPolicy: ClusterFirst
  env:
    DO_NOT_TRACK: 1
  envFrom:
    - secretRef:
        name: netdata
  configs:
    stream:
      enabled: true
      path: /etc/netdata/stream.conf
      data: |
        [stream]
          enabled = {{ ternary "yes" "no" .Values.parent.enabled }}
          destination = talos:{{ .Values.service.port }}
          api key = 11111111-2222-3333-4444-555555555555
          timeout seconds = 60
          buffer size bytes = 1048576
          reconnect delay seconds = 5
          initial clock resync iterations = 60
    go.d:
      enabled: true
      path: /etc/netdata/go.d.conf
      data: |
        default_run: no
        modules:
          k8s_state: yes
          k8s_kubelet: yes
          k8s_kubeproxy: yes
    go.d-k8s_state:
      enabled: true
      path: /etc/netdata/go.d/k8s_state.conf
      data: |
        jobs:
          - name: k8s_state
            update_every: 1
    go.d-k8s_kubelet:
      enabled: true
      path: /etc/netdata/go.d/k8s_kubelet.conf
      data: |
        jobs:
          - name: k8s_kubelet
            update_every: 1
    go.d-k8s_kubeproxy:
      enabled: true
      path: /etc/netdata/go.d/k8s_kubeproxy.conf
      data: |
        jobs:
          - name: k8s_kubeproxy
            update_every: 1
