image:
  tag: edge

restarter:
  enabled: true

ingress:
  enabled: false

parent:
  database:
    persistence: true
    storageclass: "longhorn"
    volumesize: 50Gi
  # env:
  #   DO_NOT_TRACK: 1
  envFrom:
    - secretRef:
        name: netdata
  claiming:
    enabled: true
    rooms: "55384689-a02b-45d6-81aa-3614cf7c9f16"

child:
  env:
    DO_NOT_TRACK: 1
  hostNetwork: false
  envFrom:
    - secretRef:
        name: netdata
  claiming:
    enabled: true
    rooms: "55384689-a02b-45d6-81aa-3614cf7c9f16"

k8sState:
  env:
    DO_NOT_TRACK: 1
  # envFrom:
  #   - secretRef:
  #       name: netdata
  # claiming:
  #   enabled: true
  #   rooms: "1197d4e3-4d17-4ce2-a678-31c4363e4571"
