image:
  tag: stable

restarter:
  enabled: true

parent:
  database:
    persistence: true
    storageclass: "longhorn"
    volumesize: 50Gi
  env:
    DO_NOT_TRACK: 1
  envFrom:
    - secretRef:
        name: Netdata
  claiming:
    enabled: true
    rooms: "1197d4e3-4d17-4ce2-a678-31c4363e4571"

child:
  env:
    DO_NOT_TRACK: 1
  envFrom:
    - secretRef:
        name: netdata
  claiming:
    enabled: true
    rooms: "1197d4e3-4d17-4ce2-a678-31c4363e4571"

k8sState:
  env:
    DO_NOT_TRACK: 1
  envFrom:
    - secretRef:
        name: netdata
  claiming:
    enabled: true
    rooms: "1197d4e3-4d17-4ce2-a678-31c4363e4571"
