image:
  tag: stable

restarter:
  enabled: false

ingress:
  enabled: false

parent:
  database:
    persistence: true
    storageclass: "longhorn"
    volumesize: 100Gi
  # env:
  #   DO_NOT_TRACK: 1
  envFrom:
    - secretRef:
        name: netdata
  claiming:
    enabled: true
    rooms: "55384689-a02b-45d6-81aa-3614cf7c9f16"
  configs:
    netdata:
      enabled: true
      path: /etc/netdata/netdata.conf
      data: |
        [global]
          hostname = {{ .Values.parent.hostname }}
        [db]
          mode = dbengine
          storage tiers = 3
          dbengine tier 0 retention size = 40GiB
          dbengine tier 0 retention time = 3Mo
          dbengine tier 1 retention size = 30GiB
          dbengine tier 1 retention time = 12mo
          dbengine tier 2 retention size = 10GiB
          dbengine tier 2 retention time = 4y
        [plugins]
          cgroups = yes
          tc = no
          enable running new plugins = no
          check for new plugins every = 72000
          python.d = no
          charts.d = yes
          go.d = yes
          node.d = yes
          apps = yes
          proc = yes
          idlejitter = no
          diskspace = yes
          devstat = yes
          getmntinfo = yes

child:
  dnsPolicy: ClusterFirst
  env:
    DO_NOT_TRACK: 1
  hostNetwork: false
  envFrom:
    - secretRef:
        name: netdata
  claiming:
    enabled: true
    rooms: "55384689-a02b-45d6-81aa-3614cf7c9f16"

k8sState:
  dnsPolicy: ClusterFirst
  env:
    DO_NOT_TRACK: 1
  envFrom:
    - secretRef:
        name: netdata
  claiming:
    enabled: true
    rooms: "55384689-a02b-45d6-81aa-3614cf7c9f16"
