image:
  tag: stable

restarter:
  enabled: false

ingress:
  enabled: false

parent:
  database:
    persistence: true
    storageclass: "longhorn"
    volumesize: 50Gi
  # env:
  #   DO_NOT_TRACK: 1
  envFrom:
    - secretRef:
        name: netdata
  claiming:
    enabled: true
    rooms: "55384689-a02b-45d6-81aa-3614cf7c9f16"
  configs:
    netdata:
      enabled: true
      path: /etc/netdata/netdata.conf
      data: |
        [global]
          hostname = {{ .Values.parent.hostname }}
        [db]
          mode = dbengine

        [plugins]
          cgroups = yes
          tc = no
          enable running new plugins = no
          check for new plugins every = 72000
          python.d = no
          charts.d = yes
          go.d = yes
          node.d = yes
          apps = yes
          proc = yes
          idlejitter = yes
          diskspace = yes

child:
  dnsPolicy: ClusterFirst
  env:
    DO_NOT_TRACK: 1
  hostNetwork: false
  envFrom:
    - secretRef:
        name: netdata
  claiming:
    enabled: true
    rooms: "55384689-a02b-45d6-81aa-3614cf7c9f16"
  configs:
    exporting:
      enabled: true
      path: /etc/netdata/exporting.conf
      data: ""

k8sState:
  dnsPolicy: ClusterFirst
  env:
    DO_NOT_TRACK: 1
  envFrom:
    - secretRef:
        name: netdata
  claiming:
    enabled: true
    rooms: "55384689-a02b-45d6-81aa-3614cf7c9f16"
  configs:
    exporting:
      enabled: true
      path: /etc/netdata/exporting.conf
      data: ""
