image:
  tag: stable

restarter:
  enabled: false

ingress:
  enabled: false

parent:
  database:
    persistence: true
    storageclass: "longhorn"
    volumesize: 50Gi
  # env:
  #   DO_NOT_TRACK: 1
  envFrom:
    - secretRef:
        name: netdata
  claiming:
    enabled: true
    rooms: "55384689-a02b-45d6-81aa-3614cf7c9f16"
  configs:
    exporting:
      enabled: true
      path: /etc/netdata/exporting.conf
      data: |
        [prometheus_remote_write:prometheus]
          enabled = yes
          destination = 10.11.14.2:2003
          remote write URL path = /receive

child:
  dnsPolicy: ClusterFirst
  env:
    DO_NOT_TRACK: 1
  hostNetwork: false
  envFrom:
    - secretRef:
        name: netdata
  claiming:
    enabled: true
    rooms: "55384689-a02b-45d6-81aa-3614cf7c9f16"
  configs:
    exporting:
      enabled: true
      path: /etc/netdata/exporting.conf
      data: ""

k8sState:
  dnsPolicy: ClusterFirst
  env:
    DO_NOT_TRACK: 1
  envFrom:
    - secretRef:
        name: netdata
  claiming:
    enabled: true
    rooms: "55384689-a02b-45d6-81aa-3614cf7c9f16"
  configs:
    exporting:
      enabled: true
      path: /etc/netdata/exporting.conf
      data: ""
