configuration:
  features: EnableCSI
  backupStorageLocation:
    - name: apollo-minio
      provider: aws
      bucket: talos
      prefix: velero
      default: true
      accessMode: ReadWrite
      credential:
        name: velero-apollo-minio-access
        key: cloud
      config:
        region: minio
        s3ForcePathStyle: true
        s3Url: http://expose-apollo.velero.svc.cluster.local:9090/
        insecureSkipTLSVerify: true
  volumeSnapshotLocation:
    - name:
      provider: aws
      bucket: talos
      prefix: velero
      credential:
        name: velero-apollo-minio-access
        key: cloud
      config:
        region: minio
        s3ForcePathStyle: true
        s3Url: http://expose-apollo.velero.svc.cluster.local:9090/

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.12.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins
