{{- range .Values.infisicalSecrets }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecrets-{{ .name }}
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: talos
        envSlug: prod
        secretsPath: "/{{ .path }}/"
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical

  managedKubeSecretReferences:
    - secretName: {{ .name }}
      secretNamespace: {{ .namespace}}
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: false
        data:
            {{- range .keys }}
                {{ . }}: "{{`{{ .`}}{{ . }}{{`.Value }}`}}"
            {{- end }}
---
{{- end }}