apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaContactPoint
metadata:
  name: grafana-contactpoint-telegram
  namespace: monitoring-system
spec:
  name: telegram-alerts
  type: telegram
  instanceSelector:
    matchLabels:
      dashboards: "external-grafana"
  settings:  
    chatid: "-4835005485"
    # message: "{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}"
  valuesFrom:
    - targetPath: "settings.bottoken"
      valueFrom:
        secretKeyRef:
          name: telegram-apollobot-token
          key: TELEGRAM_APOLLOBOT_TOKEN
