apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring-system
  labels:
    dashboards: "grafana"
    app.kubernetes.io/name: grafana
spec:
  baseImage: grafana/grafana
  version: "12"

  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
  disableDefaultAdminSecret: true


  deployment:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 65534
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      key: GRAFANA_ADMIN_USERNAME
                      name: grafana-admin-credentials
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: GRAFANA_ADMIN_PASSWORD
                      name: grafana-admin-credentials
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc
      strategy:
        type: Recreate

  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: longhorn
