image:
  repository: docker.io/syncthing/syncthing
  tag: "1"
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      http:
        port: 8384
  listen:
    enabled: true
    type: NodePort
    externalTrafficPolicy: Local
    ports:
      listen:
        enabled: true
        port: 22000
        protocol: TCP
        targetPort: 22000
  discovery:
    enabled: true
    type: NodePort
    externalTrafficPolicy: Local
    ports:
      discovery:
        enabled: true
        port: 21027
        protocol: UDP
        targetPort: 21027

persistence:
  data:
    enabled: true
    mountPath: /var/syncthing
    existingClaim: syncthing-vol