apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-immich-nfs
  namespace: immich
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi             # Must be ≤ PV size