apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-1
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn  # Must match the PV
  volumeName: pvc-e333c8ea-5d60-4b8c-baed-f14af0d7d9c5  # The existing PV name