apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-immich-library
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: longhorn