multicluster:
  enabled: false

global:
  persistence:
    enabled: true
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: 20Gi
    metering:
      size: 2Gi
    catalog:
      size: 20Gi
    jobs:
      size: 20Gi
    logging:
      size: 20Gi

eula:
  accept: true
  company: "na"
  email: "na@na.na"

prometheus:
  rbac:
    create: false
  server:
    enabled: false

clusterName: "talos"

limiter:
  executorReplicas: 1

excludedApps:
  - "kube-ingress"
  - "kube-node-lease"
  - "kube-public"
  - "kube-rook-ceph"

kastenDisasterRecovery:
  quickMode:
    enabled: true

logging:
  internal: false