multicluster:
  enabled: true
  primary:
    create: true
    name: "talos"
    ingressURL: "http://localhost:2222/k10/"

global:
  persistence:
    enabled: true
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: 20Gi
    metering:
      size: 2Gi
    catalog:
      size: 19Gi
    jobs:
      size: 18Gi
    logging:
      size: 17Gi

eula:
  accept: true
  company: "na"
  email: "na@na.na"

prometheus:
  rbac:
    create: false
  server:
    enabled: false

clusterName: "talos"

limiter:
  executorReplicas: 1

excludedApps:
  - "kube-ingress"
  - "kube-node-lease"
  - "kube-public"
  - "kube-rook-ceph"

kastenDisasterRecovery:
  quickMode:
    enabled: false