multicluster:
  enabled: true
  primary:
    create: true
    name: "talos"
    ingressURL: "http://localhost:2222/k10/"

storageClass: "longhorn"

eula:
  accept: true
  company: "na"
  email: "na@na.na"

prometheus:
  rbac:
    create: false
  server:
    enabled: false

clusterName: "talos"

limiter:
  executorReplicas: 1

excludedApps:
  - "kube-ingress"
  - "kube-node-lease"
  - "kube-public"
  - "kube-rook-ceph"
