multicluster:
  enabled: false

global:
  # prometheus:
  #   external:
  #     host: prometheus-kube-prometheus-prometheus.monitoring-system.svc.cluster.local
  #     port: 9090
  persistence:
    enabled: true
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: 20Gi
    metering:
      size: 2Gi
    catalog:
      size: 20Gi
    jobs:
      size: 20Gi
    logging:
      size: 20Gi

prometheus:
  rbac:
    create: true
  server:
    enabled: true
    retention: 120d
    persistentVolume:
      storageClass: longhorn
      size: 12Gi
    fullnameOverride: prometheus-server
    baseURL: /k10/prometheus/
    prefixURL: /k10/prometheus

eula:
  accept: true
  company: "na"
  email: "na@na.na"

prometheus:
  rbac:
    create: false
  server:
    enabled: false

clusterName: "talos"

limiter:
  executorReplicas: 1

excludedApps:
  - "kube-ingress"
  - "kube-node-lease"
  - "kube-public"
  - "kube-rook-ceph"

kastenDisasterRecovery:
  quickMode:
    enabled: true

logging:
  internal: false