apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: netpol-longhorn-common
  namespace: longhorn-system
spec:
  endpointSelector:
    matchLabels: {}
  ingress:
    - fromEndpoints:
        - matchLabels: {}
  egress:
    - toEndpoints:
        - matchLabels: {}
    - toEntities:
        - host
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
